### ISSUE TITLE
Edit your code tutorial

### ISSUE THREAD

**Issue by dade-ally** [xamarin/get-started#1]
Problem encountered on https://dotnet.microsoft.com/learn/mobile/xamarin-hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
I couldn't edit the MainPage.xaml.cs, the page is not editable in visual studio, how do I proceed? Or I need to get out of the Debug mode to do this?

**Comment by jamesmontemagno** [comment]
You will need to stop debugging mode to make the edit to the .cs file. I will update the tutorial to reflect this. Thanks for the feedback!

**Comment by jamesmontemagno** [comment]
Updated docs here and now live. Thanks for the feedback.
