### ISSUE TITLE
There is no MainPage.xaml

### ISSUE THREAD

**Issue by Andy-Baxman** [xamarin/get-started#101]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by jamesmontemagno** [comment]
Please ensure you create a "Blank" Xamarin.Forms app as outlined in the tutorial.
