### ISSUE TITLE
XCode 13 Beta support in Visual Studio

### ISSUE THREAD

**Issue by JuliusCosmoRomeo** [xamarin/get-started#102]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/run
Operating System: macos

Since upgrading to XCode 13 Beta I can't select any iOS simulator anymore. The only fix was to downgrade to XCode 12.5.

**Comment by jamesmontemagno** [comment]
For issues like this can you please use the "report a problem" feature inside of Visual Studio to report it to the team.
