### ISSUE TITLE
Help with intro Xamarin tutorial debugging issue

### ISSUE THREAD

**Issue by androidtucra** [xamarin/get-started#104]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/modify
Operating System: windows

I have the latest Windows 10 updated and the latest Microsoft Visual Studio. The problem is when I try to debug in the tutorial for xamarin during the "add button" section. 

The first error is on the MainPage.xaml and reads: 
"Severity	Code	Description	Project	File	Line	Suppression State
Error		Unexpected end of file has occurred. The following elements are not closed: ContentPage. Line 16, position 21.	App1	C:\Users\andro\source\repos\App1\App1\App1\MainPage.xaml	16	"

The next two errors seem to be the same. They are on MainPage.xaml.cs and they read the following: 
"Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1513	} expected	App1	C:\Users\andro\source\repos\App1\App1\App1\MainPage.xaml.cs	23	Active"

"Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1513	} expected		C:\Users\andro\source\repos\App1\App1\App1\MainPage.xaml.cs	23"	

I attached the screenshots here as well. Any help would be very appreciated!
![mainpage cs](https://user-images.githubusercontent.com/90637781/133136891-d1d75af7-3168-4f64-84dd-dffaddafaf1d.jpg)
![mainpage](https://user-images.githubusercontent.com/90637781/133136894-ccb86b20-06fe-482c-af10-60f957d7ed3b.jpg)

**Comment by jamesmontemagno** [comment]
So on MainPage.xaml.cs ... add a new line at the bottom (line 24) and add `}`

On MainPage.xaml add a new line at the bottom (line 17) and add `</ContentPage>`

**Comment by androidtucra** [comment]
Worked! Thank you!
