### ISSUE TITLE
No MainPage.xaml

### ISSUE THREAD

**Issue by tuckson** [xamarin/get-started#106]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Hi,

Am following the hello world tutorial. Can get the app to run nicely on my phone, but when I need to edit some code, I do not have the MainPage.xaml file anywhere. Yet I can run ok.

Did I do something wrong or I the tutorial just outdated?
I run Visual Studio 2019 Pro

**Comment by jamesmontemagno** [comment]
Did you create an Android app or a Xamarin.Forms app?

**Comment by tuckson** [comment]
I have an android map and an ios map inside the sultion, so I guess I did the xamarin forms
--
Verstuurd via de Mail.ru-app voor Android vrijdag, 24 september 2021, 07:19p.m. +02:00 van James Montemagno  ***@***.*** :

**Comment by jamesmontemagno** [comment]
You should see this when you create a new Xamarin.Forms project -> 
![image](https://user-images.githubusercontent.com/1676321/134785292-97c36a28-3108-46a0-98c7-fbbc3ee4429e.png)


If you don't see that top project there may be some error in your installation. Run a repair on visual studio and that shoudl fix it up.

**Comment by dinther** [comment]
I have a similar issue. I think I followed the instructions here to the letter but these day's nothing works it seems.
https://dotnet.microsoft.com/en-us/learn/xamarin/hello-world-tutorial/modify

Although, the project does compile and run on the android device connected to the USB port. The fact that worked blew me away.

![image](https://user-images.githubusercontent.com/1192916/146889011-1b191954-eb42-4438-9b1b-360f95441f32.png)

**Comment by jamesmontemagno** [comment]
@dinther you created a Flyout or Tabbed app. The tutorial walks through creating a "Blank" app

![image](https://user-images.githubusercontent.com/1676321/147688797-7153645b-b47f-4562-a1d0-d9ded3cd053c.png)
