### ISSUE TITLE
Had the error ADB0010, could be becuase of some sdk's I perhaps forgot to download?

### ISSUE THREAD

**Issue by HanTenma** [xamarin/get-started#108]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by jamesmontemagno** [comment]
Can you elaborate more on this issue. Did you get it fixed up?
