### ISSUE TITLE
metadata .dll could not be found & package system.numerics.vectors 4.5.0 is not compatible .....

### ISSUE THREAD

**Issue by abdullahaltun70** [xamarin/get-started#110]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/devicesetup
Operating System: windows

I am new to C# and I am trying to build an app with xamarin. But when i try to start the app I get the two following error 
messages:

Message1:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file 'C:\Users\user\Documents\Test C# app\TestApp\TestApp\bin\Debug\netstandard2.0\ref\TestApp.dll' could not be found	TestApp.Android	C:\Users\user\Documents\Test C# app\TestApp\TestApp.Android\CSC	1	Active 

Message 2:

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package System.Numerics.Vectors 4.5.0 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package System.Numerics.Vectors 4.5.0 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - netcoreapp2.0 (.NETCoreApp,Version=v2.0)
  - uap10.0.16299 (UAP,Version=v10.0.16299)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)	TestApp	C:\Users\aaltu\Documents\Test C# app\TestApp\TestApp\TestApp.csproj	1	

I already tried a new clean project and reinstalling visual studio. None of those tries succeeded.

If you need other information please let me know.

Any help suggestions?

**Comment by jamesmontemagno** [comment]
The warning shouldn't be an issue at all. Can you attach your project so I can look at it?
