### ISSUE TITLE
Error with Android Mono version and .Net framework compatibiltiy

### ISSUE THREAD

**Issue by ghost** [xamarin/get-started#113]
NU1201	Project NermeenPieLibrary.Core is not compatible with monoandroid81 (MonoAndroid,Version=v8.1). Project NermeenPieLibrary.Core supports: netcoreapp3.1 (.NETCoreApp,Version=v3.1)	NermeenPieShopMobile2	C:\Users\nerme\source\repos\NermeenPieShopMobile\NermeenPieShopMobile2\NermeenPieShopMobile2.csproj

I am having this kind of error when i added core project as reference to another solution.?i don't know what is wrong.
let me show screen shot of Android App, and .core library settings.

![Screenshot 2021-09-23 213251](https://user-images.githubusercontent.com/89212064/137686051-be81a4c5-e17f-4ba8-abbb-46069b1bf612.png)
![Screenshot 2021-10-18 002053](https://user-images.githubusercontent.com/89212064/137686053-989b2b3c-866c-4d01-a9cf-a5da2d41f9d3.png)

i don't know how to update .net core to .net standard or keep all at same version of .NEt standard?

**Comment by jamesmontemagno** [comment]
Ah yes, that is correct. You will want ot create a ".NET Standard Library" not a .NET Library. 

With .NET 6 this will be enabled.

**Comment by jamesmontemagno** [comment]
Checkout https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/code-sharing#Net_Standard

**Comment by ghost** [comment]
Thank you so much for this help. I will refer to this in my blog for sure
