### ISSUE TITLE
Walkthrough is flawed

### ISSUE THREAD

**Issue by sqlguy6212** [xamarin/get-started#117]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/devicesetup
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Instructions ask you to do something that is really not defined.  As it is in the start of the walkthrough it makes it useless.

**Comment by jamesmontemagno** [comment]
Can you elaborate a bit more on what is not defined?
