### ISSUE TITLE
Edit Your Code in Xamarin Tutorial

### ISSUE THREAD

**Issue by tarlini14** [xamarin/get-started#12]
On the video walk through for Xamarin Tutorial "Edit Your Code", it doesn't show the code being edited to create the button. I'm trying to follow the directions, but I keep getting errors. Which lines are each pieces of code supposed to pasted to to create the button?

https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/modify

**Comment by jamesmontemagno** [comment]
You will want to modify both the MainPage.xaml and the MainPage.xaml.cs:

![image](https://user-images.githubusercontent.com/1676321/77870936-980bea80-71f7-11ea-9050-329a52c51db4.png)
