### ISSUE TITLE
Xamarin no longer supported?

### ISSUE THREAD

**Issue by chrisfgonzales** [xamarin/get-started#120]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/install
Operating System: windows

Based on the options shown in the 2022 tutorial for Xamarin the option for Xamarin mobile development should be available. As shown in the screen shot below, my installation is saying that Xamarin is no longer supported. Please advise.

![image](https://user-images.githubusercontent.com/118977/145093090-2aab59f4-53b0-47a8-aeaf-cab3ead7429c.png)

**Comment by jamesmontemagno** [comment]
Oh strange.... that is not what I see at all...

![image](https://user-images.githubusercontent.com/1676321/145305103-3a567dcf-bcad-4771-9795-edf4ee7f2764.png)


Whate version does it say you are installing? "Mobile development with JavaScript" looks like it is Visual Studio 2017...

**Comment by chrisfgonzales** [comment]
It was VS2017. Downloaded 2022 and it is fine.
