### ISSUE TITLE
Xamarian Tutorial:Edit your code.

### ISSUE THREAD

**Issue by Hetp856** [xamarin/get-started#121]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/xamarin/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
In Edit your code phase, the first step is to double click on MainPage.Xaml however, I can't seem to find it on my computer 
![Screenshot 2021-12-09 205434](https://user-images.githubusercontent.com/95895656/145509432-7383f5bf-ff36-4f13-b536-2b3769135a81.jpg)
.

**Comment by jamesmontemagno** [comment]
You need to select the "Blank" template
![image](https://user-images.githubusercontent.com/1676321/146275331-b6197173-f73c-4aa6-8b26-3afa9b015d64.png)
