### ISSUE TITLE
no blank forms app

### ISSUE THREAD

**Issue by JeanmarieJackman** [xamarin/get-started#123]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/xamarin/hello-world-tutorial/create
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by jamesmontemagno** [comment]
Ah yes they re-named it..

Multiplatform -> App -> Blank App (under Xamarin.Forms)
