### ISSUE TITLE
Device Emulation Not Supported

### ISSUE THREAD

**Issue by pwinch** [xamarin/get-started#124]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/xamarin/hello-world-tutorial/devicesetup
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by pwinch** [comment]
My processor is: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz   2.42 GHz
I am running Visual Studio 2022 on a HP Pavilion x360 14-dw1xx

8 GB or RAM

64bit Operating system (Windows 10)

**Comment by jamesmontemagno** [comment]
For emulator setup can you check https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/
