### ISSUE TITLE
Deployment failed for xamarin using adroid device

### ISSUE THREAD

**Issue by arepadeperemi** [xamarin/get-started#125]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/xamarin/hello-world-tutorial/run
Operating System: windows

I ran into an issue trying to deploy xamarin to my android device with the debug option
I get an error saying

**Comment by jamesmontemagno** [comment]
Please see https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/set-up-device-for-development
