### ISSUE TITLE
bruh

### ISSUE THREAD

**Issue by fgclue** [xamarin/get-started#126]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/xamarin/hello-world-tutorial/install#
Operating System: windows

i cant actually choose where to install the entire thing

**Comment by fgclue** [comment]
i wanna install it to x:\ (fully) but it wont let me

**Comment by jamesmontemagno** [comment]
See: https://docs.microsoft.com/en-us/visualstudio/install/install-visual-studio?view=vs-2022#step-7---select-the-installation-location-optional

For feedback on Visual Studio head to https://developercommunity.visualstudio.com/search?space=8
