### ISSUE TITLE
help

### ISSUE THREAD

**Issue by awpie** [xamarin/get-started#127]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/xamarin/hello-world-tutorial/devicesetup
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

When I try to run the android emulator, it says "Resetting for cold boot Emulator Engine Failed", and I get a black screen.
OS: Windows 11 Home

**Comment by jamesmontemagno** [comment]
Please checkout the documentation for android emulator setup -> https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/

The google emulator may not be compatible with your device.
