### ISSUE TITLE
Tengo un error al ejecutar el emulador, aparece que tengo que descargar intel XAM

### ISSUE THREAD

**Issue by JohnAndrIOS** [xamarin/get-started#128]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/xamarin/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by jamesmontemagno** [comment]
Take a look at the Android emulator setup guide https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/
