### ISSUE TITLE
Invalid ID with OnePlus and blank xamarin forms app

### ISSUE THREAD

**Issue by BasDeJong007** [xamarin/get-started#129]
Hi i'm working on my first Xamarin app,

Currently i'm programming using Visual Studio 2022 on Windows 11, by making use of the blank template app (for both IOS and Android) I got Invalid ID messages in my output while running the app on my phone (OnePlus NORD, Android 11, Api 30) by pressing the "play" button in VS.

**Output mesages for the "healthap"**
[yname.healthap] Invalid ID 0x00000002.
[yname.healthap] Invalid ID 0x00000002.
[yname.healthap] Invalid ID 0x00000003.
[yname.healthap] I Invalid ID 0x00000004.
[yname.healthap] Invalid ID 0x00000005.
[yname.healthap] Invalid ID 0x00000006.

While performance seems normal on my Android phone e.g. everything is displayed as I expect, it is clottering my output window and leaving me worrying if this could cause any bugs later on in the process.

Therefore, I'm wondering how either fix the cause of these messages or let them not showing up in the output window.

Can anyone help me, your help is appreciated!

**Comment by jamesmontemagno** [comment]
Seems to be somethign with ONePlus phones. Is being tracked here, but doesn't seem to cause any issues https://github.com/xamarin/Xamarin.Forms/issues/12893 and not sure if it just a debug thing either.
