### ISSUE TITLE
new to visual studio

### ISSUE THREAD

**Issue by 131GMAK** [xamarin/get-started#13]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
the code is filled with bugs every time i debug i encounter multiple errors and i didn't write the code it came with the app

**Comment by jamesmontemagno** [comment]
Can you please add screenshots of errors that you are running into?
