### ISSUE TITLE
I can't see a Frame element in my Mainpage.app and of course, I can't see StackLayout to paste in a code!!!

### ISSUE THREAD

**Issue by aproko234** [xamarin/get-started#136]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/xamarin/hello-world-tutorial/modify
Operating System: windows 10
Visual Studio 2022: Recently downloaded

The above header refers.

So, what do I do next because without carrying out the above function, the subsequent steps are pretty much useless.

Thanks.

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by aproko234** [comment]
I am supposed to paste the following code into StackLayout:

 <Frame BackgroundColor="DeepPink" Padding="24" CornerRadius="0">
    <Label Text="Welcome to Xamarin.Forms!" HorizontalTextAlignment="Center" TextColor="White" FontSize="36"/>
  </Frame>

**Comment by aproko234** [comment]
I have been able to sort that issue out. But, I am getting this issue when I run the debugger: 
Your GPU driver information: 
  GPU #1 
  Make: 8086
  Model: Intel (R) HD Graphics 4000
  Device ID: 0166
Some users have experienced emulator issues with this driver version. As a result, we're selecting a compatibility renderer. 
Please, check with your manufacturer to see if there is an updated driver available.

The emulator does not display properly. I even had to check for and download the latest Display Driver for my Laptop. Still the error message persists. What do I do next?

**Comment by jamesmontemagno** [comment]
Checkout https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/ for emulator help. Emulators are from Google so not too much I can help with compatibility with your machine. But you can also us a device.

**Comment by aproko234** [comment]
Great, James.

However, I have been able to sort out the issue.

I am now set to start learning how to develop my very first awesome app. 

Hope you don’t mind if I will be asking a lot of questions from now forward?

Cheers.

MD Idiake
Chief Promoter of 234Aproko Kia-Kia Lost & Found Service and Goodnewsradio.ng

Sent from Mail for Windows

From: James Montemagno
Sent: Tuesday, April 12, 2022 10:14 PM
To: xamarin/get-started
Cc: aproko234; Author
Subject: SPAM-LOW: Re: [xamarin/get-started] I can't see a Frame element in my Mainpage.app and of course, I can't see StackLayout to paste in a code!!! (Issue #136)

Checkout https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/ for emulator help. Emulators are from Google so not too much I can help with compatibility with your machine. But you can also us a device.
