### ISSUE TITLE
Android Emulator taking a really long time to start up

### ISSUE THREAD

**Issue by bigboybamo** [xamarin/get-started#140]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/xamarin/hello-world-tutorial/devicesetup
Operating System: windows

Is the first time setup supposed to take this long? Its been stuck on showing that google loading screen for about an hour

**Comment by jamesmontemagno** [comment]
Checkout our guides on using hardware acceleration for best performance: https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/

**Comment by bigboybamo** [comment]
Thanks @jamesmontemagno i actually was able to resolve my issue by enabling Hyper-V
