### ISSUE TITLE
Cannot find Xamarin to download to my computer

### ISSUE THREAD

**Issue by Kristen2481** [xamarin/get-started#149]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/xamarin/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I downloaded the Visual Studio Community 2022 so I can create my own mobile app however my system does not show an option for Xamarin to download.  There are also errors when I downloaded the Visual Studio Community.  Not sure what they are as it just states there are errors when downloading.

**Comment by jamesmontemagno** [comment]
We updated the tutorial, but also recommend moving to .NET MAUI -> https://dotnet.microsoft.com/learn/maui/first-app-tutorial/intro
