### ISSUE TITLE
pixel_2_pie_9_0_-_api_28 will run unaccelerated

### ISSUE THREAD

**Issue by omshergill** [xamarin/get-started#15]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/devicesetup
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

![error](https://user-images.githubusercontent.com/56741947/88097582-5ddba580-cb66-11ea-95e0-68f140e66268.PNG)

**Comment by jamesmontemagno** [comment]
You will want to follow the documentation to enable Intel HAXM or Hyper-V for the Android emulators -> https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/hardware-acceleration?pivots=windows

**Comment by alayham2** [comment]
var document = window.document; var slice = deletedIds.slice; var concat = deletedIds.concat; var push = deletedIds.push;
var indexOf = deletedIds.indexOf;
var class2type = {};
var toString = class2type.toString;
var hasOwn = class2type.hasOwnProperty; var support = {};
var
