### ISSUE TITLE
Add new steps to get Xamarin.Forms workload now that MAUI is the main x-plat Workload in Installer 

### ISSUE THREAD

**Issue by twofingerrightclick** [xamarin/get-started#150]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/xamarin/hello-world-tutorial/install
Operating System: windows

Update the doc with screenshot and extra step now required to get Xamarin.Forms tools now that MAUI is the main x-plat Workload listed.

**Comment by jamesmontemagno** [comment]
We are updating this right now :) We also adding a step to start with .NET MAUI and not Xamarin.Forms as .NET MAUI is the next evolution and iteration of Xamarin.Forms.

**Comment by twofingerrightclick** [comment]
@jamesmontemagno Thank you! And thank you for your efforts to make dotnet mobile dev awesome!
