### ISSUE TITLE
Clicking "Provide Feedback" does nothing

### ISSUE THREAD

**Issue by dschendt** [xamarin/get-started#151]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/xamarin/hello-world-tutorial/install#
Operating System: windows

Steps:
1) Click "I ran into a problem" button at the bottom of the page.
2) Click "Provide Feedback" option.
3) Watch popup close.

Relevant Info:
Chrome 104.0.5112.102
Windows 10 Pro 19044.1889

Additional Note: Feedback that I wanted to provide is that the option "Mobile development with .NET" doesn't appear to exist anymore in VS Code 2022 17.3.3.

**Comment by jamesmontemagno** [comment]
Hmmm I get a pop up that gives me options. maybe your browser is blocking it?

We updated the tutorial, but also recommend moving to .NET MAUI -> https://dotnet.microsoft.com/learn/maui/first-app-tutorial/intro
