### ISSUE TITLE
Visual Studio can't find Provisioning Profile ;

### ISSUE THREAD

**Issue by ssouzawallace** [xamarin/get-started#154]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/xamarin/hello-world-tutorial/run
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Visual Studio can't find Provisioning Profile ;

**Comment by mairaw** [comment]
@jamesmontemagno is this something you can help with?

**Comment by jamesmontemagno** [comment]
Please report a problem in visual studio to report to the team for follow up.
