### ISSUE TITLE
VisualStudio.Deployment.PackageManagerOperations”的类型初始值设定项引发异常。

### ISSUE THREAD

**Issue by qq447060215** [xamarin/get-started#17]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by jamesmontemagno** [comment]
Can you describe the issue that you are having?
