### ISSUE TITLE
Unable to read the NuGet.Config file

### ISSUE THREAD

**Issue by dpatil0** [xamarin/get-started#19]
I installed Visual Studio for Mac and when creating the first app getting below issue with NuGet. 

An error occurred when trying to read the NuGet.Config file. The NuGet.Config file will be treated as read-only.

Failed to read NuGet.Config due to unauthorized access. Path: '/Users/dipkishor/.config/NuGet/NuGet.Config'.

**Comment by mrward** [comment]
Visual Studio does not have permission to access that file. You should check the permissions on the file and its parent folder, or remove the NuGet directory so Visual Studio for Mac can re-create the file.

**Comment by ghost** [comment]
I got yesterday my brand new MacBook Pro m1, and before I had a windows notebook. Earlier I started programming with C# Visual Studios, therefore I wanted to keep program in visual studios. When I opened it at first, I got the problem, that I could not access the Nuge.Config file. 

After 5 hours of research, I found the solution. On my MacBook I did not have a Nuge.Config file so I had to create one on myself. First press shift + command + G and type: ~/.config . From there create a new folder called: "NuGet".
Open Link  ( to png file) for proof:
<img width="518" alt="Bildschirmfoto 2021-07-26 um 02 00 34" src="https://user-images.githubusercontent.com/87953592/126917967-1f02f147-bd97-48be-b084-6b2bd033b968.png">

In the next Step, you have to press cmd + tab (=finder) and open "Textedit". Now you write following xml script: 
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
</configuration>

<img width="640" alt="Bildschirmfoto 2021-07-26 um 02 11 34" src="https://user-images.githubusercontent.com/87953592/126918032-f04c7670-b3e0-40e1-8f52-f36f6ed2641b.png">


and save the file with the name: NuGet.Config.xml in a random place you wish, but you need to find it back. After creating the file, you basically copy the file and make the same steps with shift cmd g and place the file (by command + v)  into the NuGet folder. 
<img width="392" alt="Bildschirmfoto 2021-07-26 um 02 06 33" src="https://user-images.githubusercontent.com/87953592/126917901-a753b3c4-ab3d-4891-a1d2-931de55542c0.png">

After the delete the old NuGet.config.xml file in the random folder everything should work

If it work for you, I am happy.

**Comment by adjaydev** [comment]
This worked for me, thanks!

**Comment by BerkerSarikaya** [comment]
perfect solution thx.

**Comment by vasanthsai27** [comment]
thanks dude, its working

**Comment by nfhisey** [comment]
Thank you this worked perfectly!

**Comment by monteroaurea** [comment]
it doesn't work for me. when you type shift + command + G (this is the terminal for you? not for me) anyway even opening the .config directory on the terminal when I try to create a new directory there I have permission denied. even try pushing it with "force" doesn't work

**Comment by nfhisey** [comment]
@aurea94  shift + command + G will not open terminal but a file finder. You will then type in ~/.config into the file finder and it will open the config directory in finder which is shown in the first screen shot. I hope this helps

**Comment by monteroaurea** [comment]
> @aurea94 shift + command + G will not open terminal but a file finder. You will then type in ~/.config into the file finder and it will open the config directory in finder which is shown in the first screen shot. I hope this helps

it did thank you

**Comment by konstanzer** [comment]
If you create the NuGet subdirectory in .config, the NuGet.config file should generate automatically

**Comment by dougasssis** [comment]
Thanks for the solution step by step!!! =))) but in my case when I created the directory it automatically created a NuGet.Config file inside it!

**Comment by rahimdev786** [comment]
Give Full  Disk Access in setting  to VScode ...
that its issue is Fix..
