### ISSUE TITLE
installed visual studio but the layout xaml page shows a black screen.

### ISSUE THREAD

**Issue by manicenterprise** [xamarin/get-started#20]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by jamesmontemagno** [comment]
This could just be that the emulator did not start all the way. Emulators will take much time to start and you will see a home screen. It can take several minutes if you did not enable acceleration.
