### ISSUE TITLE
Problem downloading

### ISSUE THREAD

**Issue by Shepherdswork** [xamarin/get-started#21]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. 

Operating System: Windows 10 Pro 64-bit 10.0 18363

Message Errors:
Something went wrong with the install.

You can troubleshoot the package failures by:

    1. Search for solutions using the search URL below for each package failure
    2. Modify your selections for the affected workloads or components and then retry the installation
    3. Remove the product from your machine and then install again

If the issue has already been reported on the Developer Community, you can find solutions or workarounds there. If the issue has not been reported, we encourage you to create a new issue so that other developers will be able to find solutions or workarounds. You can create a new issue from within the Visual Studio Installer in the upper-right hand corner using the "Provide feedback" button.

================================================================================

Package 'AndroidBuildTools_Xamarin,version=28.0.3.0' failed to download from 'https://aka.ms/android-sdk_build-tools_r28.0.3-windows'.
    Search URL
        https://aka.ms/VSSetupErrorReports?q=PackageId=AndroidBuildTools_Xamarin;PackageAction=DownloadPackage;ReturnCode=0x80072f0d
    Details
        WebClient download failed: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
        Bits download failed: File not found.
        WinInet download failed: Function: InternetOpenUrl, HR: -2147012851, Message: Unknown error 12045
    Impacted workloads
        Mobile development with .NET (Microsoft.VisualStudio.Workload.NetCrossPlat,version=16.5.29514.35)
    Impacted components
        Android SDK setup (API level 28) (Component.Android.SDK28,version=16.2.29003.222)

--------------------------------------------------------------------------------

Package 'AndroidPlatformTools_Xamarin,version=28.0.2.0' failed to download from 'https://aka.ms/android-sdk_platform-tools_r28.0.2-windows'.
    Search URL
        https://aka.ms/VSSetupErrorReports?q=PackageId=AndroidPlatformTools_Xamarin;PackageAction=DownloadPackage;ReturnCode=0x80072f0d
    Details
        WebClient download failed: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
        Bits download failed: File not found.
        WinInet download failed: Function: InternetOpenUrl, HR: -2147012851, Message: Unknown error 12045
    Impacted workloads
        Mobile development with .NET (Microsoft.VisualStudio.Workload.NetCrossPlat,version=16.5.29514.35)
    Impacted components
        Android SDK setup (API level 28) (Component.Android.SDK28,version=16.2.29003.222)

--------------------------------------------------------------------------------

Package 'AndroidTools_Xamarin,version=26.1.1.5' failed to download from 'https://go.microsoft.com/fwlink/?linkid=869046'.
    Search URL
        https://aka.ms/VSSetupErrorReports?q=PackageId=AndroidTools_Xamarin;PackageAction=DownloadPackage;ReturnCode=0x80072f0d
    Details
        WebClient download failed: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
        Bits download failed: File not found.
        WinInet download failed: Function: InternetOpenUrl, HR: -2147012851, Message: Unknown error 12045
    Impacted workloads
        Mobile development with .NET (Microsoft.VisualStudio.Workload.NetCrossPlat,version=16.5.29514.35)
    Impacted components
        Android SDK setup (API level 28) (Component.Android.SDK28,version=16.2.29003.222)

--------------------------------------------------------------------------------

Package 'AndroidPlatform28,version=1.0.0' failed to download from 'https://aka.ms/android-sdk_platform-28_r06'.
    Search URL
        https://aka.ms/VSSetupErrorReports?q=PackageId=AndroidPlatform28;PackageAction=DownloadPackage;ReturnCode=0x80072f0d
    Details
        WebClient download failed: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
        Bits download failed: File not found.
        WinInet download failed: Function: InternetOpenUrl, HR: -2147012851, Message: Unknown error 12045
    Impacted workloads
        Mobile development with .NET (Microsoft.VisualStudio.Workload.NetCrossPlat,version=16.5.29514.35)
    Impacted components
        Android SDK setup (API level 28) (Component.Android.SDK28,version=16.2.29003.222)

**Comment by jamesmontemagno** [comment]
Please double check your internet connection and vpn settings. YOu can manually install SDKs via: https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-sdk
