### ISSUE TITLE
No prompt to accept android license when following xamarin walkthrough

### ISSUE THREAD

**Issue by dovholuknf** [xamarin/get-started#23]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/create
Operating System: windows

After creating new "Awesome App" I was not prompted to accept the Android license. After closing and reopening the project - I *did* get the prompt as shown in the doc.

**Comment by jamesmontemagno** [comment]
Thanks for the feedback. It may pop up on build as well. It depends on the system. I will ask the team.

**Comment by jamesmontemagno** [comment]
I believe this is just a matter of timing and newer builds improve on this.
