### ISSUE TITLE
Device error: Could not get emulator name after starting AVD pixel_2_nougat_7_1_api_25

### ISSUE THREAD

**Issue by mma42300** [xamarin/get-started#25]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/devicesetup
Operating System: windows

![image](https://user-images.githubusercontent.com/7395067/91064370-717b9f80-e62f-11ea-80d2-69679ee9247e.png)

operating system version : Windows 10 Pro 1903.

**Comment by jamesmontemagno** [comment]
Can you delete this emulator and create a new one?

**Comment by candidodmv** [comment]
I am getting the same error, even after remove and create a new one

**Comment by jamesmontemagno** [comment]
Checkout the docs on emulators: https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/

**Comment by zlbcdn** [comment]
i have the same problem,there is my way

go to path of your android emulator, my path is : **C:\Users\Administrator.android\avd\pixel_5_-android11.avd**

and get the file : **config.ini** , open it

and then change the setting : **hw.gpu.mode=auto**  to  **hw.gpu.mode=off**

and have a try
