### ISSUE TITLE
Visual studio Previewer not working.

### ISSUE THREAD

**Issue by khadkaPratik** [xamarin/get-started#3]
Problem encountered on https://dotnet.microsoft.com/learn/mobile/xamarin-hello-world-tutorial/install
Operating System: Windows 10

Hello Team,
I am using visual studio community edition 2019 in my windows 10 device with i5 processor and 256gb SSD. The system has shown no lags till date to the task that is thrown at it but recently I am expressing a problem regarding the app previewer on visual studio although the app works fine on my debugging device but does not show in the previewer.
After trying tips from online forms now I am reinstalling the whole application form the download stage. 
Please update the solution regarding the issue. Thank you.

**Comment by jamesmontemagno** [comment]
For issues with the IDE and previewer can you please use the Report an Issue button inside of Visual Studio: https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019 this will help the team triage it.
