### ISSUE TITLE
Emulator Error

### ISSUE THREAD

**Issue by ghost** [xamarin/get-started#30]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/devicesetup
Operating System: windows

up until pressing the start of the emulated device, everything had installed fine. Once start was pressed a pop-up would appear saying Emulator error at the top and Device error: Unknown error inside the pop-up. I have deleted the simulated device multiple times as well as 'repaired' the install of the android device manager. I looked into the file path of the emulated device and found that two of the disk files were corrupted to I deleted them and reinstalled them but alas...

**Comment by jamesmontemagno** [comment]
Checkout the docs on emulators: https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/
