### ISSUE TITLE
Package xamarin failed to install.

### ISSUE THREAD

**Issue by mirulnorazmi** [xamarin/get-started#31]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/run
Operating System: windows

Package 'Microsoft.VisualStudio.Xamarin.PclProfiles,version=1.0.9.1' failed to install.
Search URL
        https://aka.ms/VSSetupErrorReports?q=PackageId=Microsoft.VisualStudio.Xamarin.PclProfiles;PackageAction=Install;ReturnCode=1603
    Details
        MSI: C:\ProgramData\Microsoft\VisualStudio\Packages\Microsoft.VisualStudio.Xamarin.PclProfiles,version=1.0.9.1\Xamarin.PclProfiles.1.0.9.msi, Properties:  REBOOT=ReallySuppress ARPSYSTEMCOMPONENT=1 
        Return code: 1603
        Return code details: Fatal error during installation.

i try reinstall it didn't work, any other option?

**Comment by jamesmontemagno** [comment]
Please perform a restore on Visual Studio or install Visual Studio 2022
