### ISSUE TITLE
Build error while build xamarin form (from very basic xamarin tutorial)

### ISSUE THREAD

**Issue by rudinarada** [xamarin/get-started#32]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I just follow the instructions from this tutorial.
1. Setting the android device for USB debugging (done)
2. Connect USB to laptop (done) - My device name showup on visual studio
3. Click Debug -> Start Debugging
4. 2 Errors rise, I include the screenshot of this errors.

Please advise.
Thank you.

![xamarin_err](https://user-images.githubusercontent.com/9031078/92344276-39289680-f0f0-11ea-8525-86f71d52f6bb.JPG)

**Comment by jamesmontemagno** [comment]
Please do a restore on Visual STudio. Looks like something did not install correct.
