### ISSUE TITLE
Visual Studio: Error starting Android Emulator

### ISSUE THREAD

**Issue by amrit7** [xamarin/get-started#33]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/devicesetup
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Using the Hello World Xamarin example in Visual Studio - I'm unable to start the Android Emulator. 

When I click on the Run button in the Android Device Manager - the error appears immediately (See attached)
 
![Error-AndroidDeviceManager](https://user-images.githubusercontent.com/13454662/93798863-3ff9f200-fc36-11ea-97ac-0ad450d78461.PNG)

**Emulator error**

Device error: WARNING: unexpected '-prop' value ('monodroid.avdname=pixel_2_pie_9_0_-_api_28'), only 'qemu.' properties are supported
WARNING: unexpected '-prop' value ('emu.uuid=4b63b139-cc77-4b66-9200-0d25f8fc545e'), only 'qemu.' properties are supported

**Windows Specifications**
   Edition: Windows 10 Pro
   Version: 1909

**Processor**
  AMD Ryzen 9 

**Task Manager:** 
   Performance: Virtualization is Enabled

**cmd - systeminfo:**
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

**Windows Features On/Off** (see attached - shows Hyper V / Virtualization enabled as per documentation):
![WindowsFeatures](https://user-images.githubusercontent.com/13454662/93798475-a599ae80-fc35-11ea-8f89-44341f3d4076.PNG)

**Comment by Mainframe79** [comment]
I just ran into this on my system as well. VS2019 with the Xamarin forms mobile template

Windows Specifications
Edition: Windows 10 Pro
Version: 1909

Processor
Core i5 7400

 Virtualization is Enabled

VM Monitor Mode Extensions: Yes
Virtualization Enabled In Firmware: Yes

**Comment by jamesmontemagno** [comment]
Checkout the docs on emulators: https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/
