### ISSUE TITLE
The instructions don't match the options within the app

### ISSUE THREAD

**Issue by yb66** [xamarin/get-started#34]
Hi there,

Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/create

Operating System: macOS 10.14.6
Visual Studio for Mac v8.6.5 build 23

The instructions given are:

> Create a new Xamarin app:
> 
>     Open Visual Studio 2019.
>     Select Create a new project.
>     Select Mobile from the Project type drop-down.
>     Select the Mobile App (Xamarin.Forms) template and click Next.
>     Enter AwesomeApp as the project name and click Create.
>     Select the Blank template. Ensure Android and iOS are both selected, and click OK.
> 

There is no "Mobile" in the Project type drop-down. There is no "Mobile App" to choose from, there is no Xamarin.Forms template.

![Screenshot 2020-09-22 at 08 44 03](https://user-images.githubusercontent.com/326444/93832339-f1b01780-fc64-11ea-91ac-548fbd0cd1bc.png)

I've checked that I have Xamarin installed and Mono.

Regards,
iain

**Comment by jamesmontemagno** [comment]
You will want to select Multiplatform in the UI ->
Select Multiplatform > App > Blank Forms App and click Next

**Comment by jamesmontemagno** [comment]
mac sure you are on the macOS tab
![image](https://user-images.githubusercontent.com/1676321/93844620-a7259f80-fc52-11ea-9ae8-a954f426a5e4.png)
