### ISSUE TITLE
I am not able to install Intel HAXM installer in my system. My system is having OS of Windows 10. Can anybody help with this

### ISSUE THREAD

**Issue by shivarajkamurthy** [xamarin/get-started#37]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/devicesetup
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by jamesmontemagno** [comment]
Please see: https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/
