### ISSUE TITLE
VS 2019 for linux

### ISSUE THREAD

**Issue by Sambhrama754** [xamarin/get-started#38]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/install
Operating System: linux

MAKE VISUAL STUDIO FOR LINUX
PARROT OS.

**Comment by Sambhrama754** [comment]
MS.PLS

**Comment by jamesmontemagno** [comment]
Xamarin is supported in Visual Studio 2019 and Visual Studio 2019 for Mac. Please open visual studio related requests: https://developercommunity.visualstudio.com/spaces/8/index.html
