### ISSUE TITLE
windows 32 bit

### ISSUE THREAD

**Issue by comando-c** [xamarin/get-started#39]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by comando-c** [comment]
Hi All

I need Xamarine for 32 bit windows.

Can someone share link.

Currently using Intel I3 processor 32 bit, Windows 7 32 bit

**Comment by jamesmontemagno** [comment]
Should work alright: https://docs.microsoft.com/en-us/visualstudio/releases/2019/system-requirements#visual-studio-2019-system-requirements when you install Visual Studio 2019
