### ISSUE TITLE
/.config file permission denied

### ISSUE THREAD

**Issue by geophal** [xamarin/get-started#40]
When I tried to download Visual Studio for Mac, I was getting "Android components can not download due to wrong permission, change the permission of /.config file." message for Android. I can not enter to the /.config via terminal also.  What am I supposed to do? 
![3B78D2F0-0CCA-4FC7-868D-73B961186D1B](https://user-images.githubusercontent.com/68911685/95979860-f65f8a00-0e24-11eb-9193-4e203cb08d12.jpeg)

**Comment by jamesmontemagno** [comment]
@jongalloway thoughts? who to send to?

**Comment by jongalloway** [comment]
Not sure, checking on this.

**Comment by geophal** [comment]
fixed problem by using

$ sudo chown -R <username> .config
