### ISSUE TITLE
Unable to change Target .NET Framework to latest version(4.7.2 or 4.8) while creating xamarin form project

### ISSUE THREAD

**Issue by kamalpradhan1** [xamarin/get-started#42]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/create
Operating System: windows

While creating Xamarin Form new project, I am not getting Target Framework option to change to latest version(.NET Framework 2.7.2). Please help me .

**Comment by jamesmontemagno** [comment]
There is no need to change any Target Framework option as Xamarin iOS/Android apps have their own version of .NET and don't run on the .NET Framework.
