### ISSUE TITLE
Can't get Visual Studio on Chrome OS?

### ISSUE THREAD

**Issue by aashrithnalluri** [xamarin/get-started#44]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/install
Operating System: Chrome OS

I can't do a thing on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/install because I have a Chrome OS operating system. Can someone please help?

**Comment by jamesmontemagno** [comment]
Visual Studio is available on Windows and macOS.
