### ISSUE TITLE
Getting Error while creating new project

### ISSUE THREAD

**Issue by ideepakwork** [xamarin/get-started#45]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Getting Error while creating new project
General Exception (Exception from HRESULT: 0x80131500

**Comment by jamesmontemagno** [comment]
Can you provide a screenshot?
