### ISSUE TITLE
EventHandler "Handle_clicked" with correct signature not found in type "Awesome.MainPage"

### ISSUE THREAD

**Issue by silnshadow** [xamarin/get-started#46]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/modify
Operating System: Windows 10

Severity	Code	Description	Project	File	Line	Suppression State
Error	XFC0002	EventHandler "Handle_Clicked" with correct signature not found in type "Awesome.MainPage".	TestApp1	P:\C# .NET class\TestApp1\Awesome\MainPage.xaml	10

**Comment by jamesmontemagno** [comment]
Hey there, Yes you will see this until you add it into the code behind. I have added some information into the tutorial.

**Comment by Natale-J** [comment]
Hi James.  I know your background and very impressive. In this current example. I have tried several different approaches that were suggested.  I have already added the code and the signature is correct, however it keeps saying Nope.
    private void OnEditorPropBuiltTextChanged(object sender, TextChangedEventArgs e)
    {
    }
                <Editor x:Name="editorPropYearBuilt"
                    Placeholder="Year built"
                    Text="Year Built"
                    WidthRequest="82"
                    FontSize="12"
                    FontAttributes="Bold"
                    IsEnabled="True"
                    BackgroundColor="LightGreen"
                    TextColor="Black"
                    HorizontalTextAlignment="End"
                    VerticalTextAlignment="End"
                    **TextChanged="onEditorPropBuiltTextChanged"**
                    Completed="OnEditorPropBuiltTextCompleted" 
                    HorizontalOptions="Center" />

I have tried removing it and re adding it.. I have done the same with the the code behind.  I have deleted the obj and the bin. I have tried clean the project, clean the solution.  I know the params are correct. I have been working on this project for a while and I did change one xml/cs from one group to another and I don't see a problem with it.  I have renamed the code behind and the same with the object itself.. I have save the project and brought it back up.  I am at a loss with this sone.  thanks Natale J
