### ISSUE TITLE
AwesomeApp tutorial

### ISSUE THREAD

**Issue by rickmedlin** [xamarin/get-started#47]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/create
Operating System: Windows

When trying to do this tutorial I get the following error:

Severity	Code	Description	Project	File	Line	Suppression State
The project AwesomeApp.Android is missing Android SDKs required for building. Double-click on this message and follow the prompts to install them.		 	0	

If I click on the message, my PC asks me for an admin password to update the Android SDK, but I don't have admin rights on my work computer.  This may be just a problem with my company's policy, but I thought I'd pass it along.

**Comment by jamesmontemagno** [comment]
Ah, that is a good one. You will need to install the Android SDK which does require admin access -> https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-sdk?tabs=windows

You also need this when you are creating emulators.
