### ISSUE TITLE
Example layout too large to fit onto standard phone screen

### ISSUE THREAD

**Issue by quilkin** [xamarin/get-started#49]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/modify
Operating System: windows

After adding the button, and running on the suggested/provided emulator (Androis-accellerated_x86_oreo), the button is off-screen so won't be seen. Not encouraging for a  first-time user!
All the text and padding above needs to be made much smaller.

**Comment by jamesmontemagno** [comment]
Thanks for the feedback. I recommend creating a new emulator as the older emulators that used to be installed were not at the correct scale. Let me know if that helps.
