### ISSUE TITLE
sudo npm install -g ios-sim

### ISSUE THREAD

**Issue by chelleyyy** [xamarin/get-started#50]
sudo npm install -g ios-sim
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ios-sim"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int

the whole npm-debug.log is attached

__Originally posted by @javaminister in https://github.com/npm/npm/issues/13918__

**Comment by jamesmontemagno** [comment]
Can you describe where/when you see this?
