### ISSUE TITLE
Android SDK won't load because it fails the Checksum.

### ISSUE THREAD

**Issue by MWMetcalfe** [xamarin/get-started#51]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Could not load the Android SDK because it failed the checksum.

**Comment by jamesmontemagno** [comment]
Are you able to open up the SDK manager an install manually: https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-sdk
