### ISSUE TITLE
Wrong instruction on "Already have Visual Studio?"

### ISSUE THREAD

**Issue by tiagonmas** [xamarin/get-started#52]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/install
Operating System: windows

In "Already have Visual Studio?" instructions, when running Visual Studio Installer, the instruction "Find your Visual Studio 2019 installation and select More > Modify" is incorrect. Latest Installer shows the Modify but directly on the interface, you do not need to hit "More".

**Comment by jamesmontemagno** [comment]
Good catch! I just added this in :) Will fix up now :)
