### ISSUE TITLE
Q about Menu selections

### ISSUE THREAD

**Issue by psansom** [xamarin/get-started#54]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/create
Operating System: macos

Macbook Pro MacOS Catalina ver 10.15.7

I am at this screen:
https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/create

the screen says:
<img width="903" alt="image" src="https://user-images.githubusercontent.com/31736902/103047850-6fc8d680-4552-11eb-8c08-1f8292888ef2.png">

But when I invoke Visual Studio it shows this:
![image](https://user-images.githubusercontent.com/31736902/103047974-c2a28e00-4552-11eb-883b-4a8053a616f3.png)

and later, after connecting my android phone it says:
<img width="730" alt="image" src="https://user-images.githubusercontent.com/31736902/103048283-aeab5c00-4553-11eb-893d-c749ba73770b.png">

So presumably, this is a menu selection where it says Solution > AwesomeApp  but I can't find where this is.

Thx!

**Comment by jamesmontemagno** [comment]
Please make sure you create a Xamarin.Forms blank app. Looks like you craeted an iOS app.
