### ISSUE TITLE
emulator error 

### ISSUE THREAD

**Issue by GavinThomas05** [xamarin/get-started#55]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/devicesetup
Operating System: windows

hi guys! I am new to programming as a whole, and i am interested in making my first mobile app. after following some tutorials on Xamarin and when I tried to run the emulator it came up with the error that I have pasted down below. 

Device error: WARNING: unexpected '-prop' value ('monodroid.avdname=pixel_2_pie_9_0_-_api_28'), only 'qemu.' properties are supported
WARNING: unexpected '-prop' value ('emu.uuid=018fc086-0f9d-4cbf-83eb-4cbb24314cb7'), only 'qemu.' properties are supported

**Comment by jamesmontemagno** [comment]
Checkout the docs on emulators: https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/
