### ISSUE TITLE
XLS0501 The property 'Default' is set more than once!

### ISSUE THREAD

**Issue by reachrajanig** [xamarin/get-started#58]
When I tried to modify the existing example as specified in Xamarin tutorial, I was getting "XLS0501 The property 'Default' is set more than once" error. Please guide on this.

**Comment by jamesmontemagno** [comment]
Hmmmm can you provide a screenshot for this of your XAML and the error. Possibly can you attach the project?

**Comment by reachrajanig** [comment]
Thank you for your quick reply. Here is the screenshot. I am using the tutorial in the Microsoft documentation. I just started learning.
![XLS0501](https://user-images.githubusercontent.com/62398483/105189345-e1208880-5b02-11eb-8b83-1b019c21dc9c.PNG)

**Comment by jamesmontemagno** [comment]
Ahhh, you need to but the button UNDER the frame.

```xml
<StackLayout>
  <Frame BackgroundColor="DeepPink" Padding="24" CornerRadius="0">
    <Label Text="Welcome to Xamarin.Forms!" HorizontalTextAlignment="Center" TextColor="White" FontSize="36"/>
  </Frame>

  <!--Add Button Here -->
  <Button Text="Click Me" Clicked="Handle_Clicked" />

  <Label Text="Start developing now" FontSize="Title" Padding="30,10,30,10" />
  <!--More Labels here -->
</StackLayout>
```
