### ISSUE TITLE
62

### ISSUE THREAD

**Issue by dersimhasan62** [xamarin/get-started#6]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/create
Operating System: undefined

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by JhonnyEVT** [comment]
windows 10 home, visual studio custom 2017

**Comment by jamesmontemagno** [comment]
Thanks for writing in, but not sure what issue you are having, will close for now.
