### ISSUE TITLE
Unhandled Exception:  System.InvalidOperationException: Cannot convert "Title" into System.Double

### ISSUE THREAD

**Issue by tanmoysaha3** [xamarin/get-started#61]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/modify
Operating System: windows
Visual studio 2019
Emulator: Oreo 8.1 - API 27 x86
![300](https://user-images.githubusercontent.com/52097315/106075485-e9e31100-6137-11eb-8f09-408df5f97fe5.PNG)
![301](https://user-images.githubusercontent.com/52097315/106076476-d173f600-6139-11eb-81fe-d9a41de732f0.PNG)
![302](https://user-images.githubusercontent.com/52097315/106076529-e94b7a00-6139-11eb-9133-bba202d99b5c.PNG)
[303.txt](https://github.com/xamarin/get-started/files/5884219/303.txt)

When trying to debugging - 
Unhandled Exception:
System.InvalidOperationException: Cannot convert "Title" into System.Double

Added code and problem as image, and code also in txt file.
Plz help me out.
Thanks.

**Comment by jamesmontemagno** [comment]
Weird.... that all looks correct. Can you try this attached solution:
[App7.zip](https://github.com/xamarin/get-started/files/5884913/App7.zip)

**Comment by jamesmontemagno** [comment]
If you could attach your project as well that would be super helpful

**Comment by tanmoysaha3** [comment]
I would be really happy if I could do that. Its size is really big. 74 mb.
However I will upload it in drive and update the link.

I ran yours code, it is good. No error.
Then I copy changed part from your code, paste it in a new solution.
But it show same error.
![307](https://user-images.githubusercontent.com/52097315/106129238-43742b80-618a-11eb-8e89-eeba9494f6a7.PNG)

**Comment by tanmoysaha3** [comment]
https://drive.google.com/file/d/1-7RAIl6VstxRk1a1ffyvWH39abVK9xtp/view?usp=sharing
My project link

**Comment by jamesmontemagno** [comment]
If you delete all of the bin/obj folders it will shrink it down a bunch :)

I opened yours up and took a look and it looks like you are using a very older version of Visual Studio as your app is using Xamarin.Forms 3.6, which is a few years old? The tutorial requires Visual Studio 2019 which I highly recommend as it is officially supported with Xamarin.Forms.

The issue is that the size "Title" was introduced later on. You can change

```
<Label Text="Start developing now" FontSize="Title"/>
```

to 
```
<Label Text="Start developing now" FontSize="30"/>
```

Although Hot Reload will not work as that is a Visual Studio 2019 feature

**Comment by jamesmontemagno** [comment]
If you delete all of the bin/obj folders it will shrink it down a bunch :)

I opened yours up and took a look and it looks like you are using a very older version of Visual Studio ? The tutorial requires Visual Studio 2019.
