### ISSUE TITLE
Пользовательские компоненты не визуализируются , так как обнаружены проблемы /  Custom components are not rendered because problems were detected

### ISSUE THREAD

**Issue by DS2107** [xamarin/get-started#64]
не могу ничего положить на форму
Can't put anything on the form
![image](https://user-images.githubusercontent.com/51126272/107030049-0ed32600-67c1-11eb-8c00-76583bde15ef.png)

**Comment by jamesmontemagno** [comment]
Tap here to get to the code -> 
![image](https://user-images.githubusercontent.com/1676321/107095640-04fbf380-67be-11eb-895a-eccf65b67505.png)

The Previewer is being phased out and we are focused on Hot Reload as the guide walks through.
