### ISSUE TITLE
application closes in execution unexpectedly

### ISSUE THREAD

**Issue by JhonnyEVT** [xamarin/get-started#7]
I have made an application but it closes when the device is locked, I need the application to continue running in the background, and when it closes, cancel the processes, since it has a loop that does not close and remains active, which does not allow to open the application until the application data is deleted

runtime error, has geolocation and sqllite database

**Comment by jamesmontemagno** [comment]
Hey there, thanks for the post, this is just for the getting started turorial. Please take a look at the background services guide: https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/services/

If you have more questions please post on our forums https://forums.xamarin.com
