### ISSUE TITLE
Incompatibility with Xcode 12.3?

### ISSUE THREAD

**Issue by azav** [xamarin/get-started#70]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/run
Operating System: macos

As soon as I installed Xamarin and ran through the tutorial, it mentions that Xcode 12 is required, NOT Xcode 12.4.

https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/install

![Screen Shot 2021-03-02 at 10 19 47 AM](https://user-images.githubusercontent.com/4999784/109679071-de24a900-7b40-11eb-870f-044e6e44c33b.png)

Then when running through the tutorial, it states that it's incompatible with Xcode 12.3, which I have installed.

https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/run

In Visual Studio V 8.8.10.2:
  
![Screen Shot 2021-03-02 at 10 16 42 AM](https://user-images.githubusercontent.com/4999784/109678641-6fdfe680-7b40-11eb-9b48-efe1c4c7a1ca.png)

Which version IS actually compatible with Xcode 12.3?   To use Xcode 12.4, I have to download and install it AND upgrade the MacOS to MacOS 11, which it may not support.

It really sucks to have the docs indicate that Xamarin will work with what I have installed only to find that it won't.  Thank you.

**Comment by azav** [comment]
It's a bit of a royal pain and still is time consuming, but this works without requiring a MacOS upgrade.

FYI this expects that you're developing on a Mac.

If you're trying to install Xamarin & build a project but aren't running the latest MacOS you'll see this error since you can't use Xcode 12.4. Don't worry. You don't have to update your Mac to macOS 11 but you will need to download Xcode 12.4. You can download a version of Xcode 12.4 from here: https://developer.apple.com/services-account/download?path=/Developer_Tools/Xcode_12.4/Xcode_12.4.xip

Unzip it in another directory, rename it to Xcode-12.4.app and move it into /Applications folder next to the other version of Xcode that you're using.

You'll have two versions of Xcode, but they'll be sitting next to each other and that's not a problem.

In Visual Studio, go to the File menu and select Preferences.

Within Preferences, select Projects > SDK Locations > Apple and in the right for location, enter this path: /Applications/Xcode-12.4.app

Quit and restart Visual Studio.

Reload your project and build for iOS. It will launch in the Simulator.

**Comment by jamesmontemagno** [comment]
I am asking the dev team to double check the latest requirements. That is just a warning so should work fine with 12.3. Double checking though.

**Comment by azav** [comment]
Thanks James.  It doesn't work with 12.3.  That's why I had this error in the first place.  

The happy news is that my instructions work to put the 12.4 version of Xcode beside 12.3 and on macOS 10.15.5 and Visual Studio is building the tutorial app in the Simulator.  

This is important because I have 2 Macs that are on 10.15.5 and Xcode 12.4 doesn't launch on them BUT, it will sit beside Xcode 12.3 and Visual Studio Xamarin builds appear to work on iOS.

**Comment by jamesmontemagno** [comment]
Talked to the team today and it is totally supported for simulator development from my understanding, just you aren't able to use newer APIs from that release.

While Xcode 12.4 does work on Cataline+ I believe from the looks that 12.5 is dropping support. Apple moves pretty fast.

Here is a good doc: https://docs.microsoft.com/en-us/xamarin/ios/troubleshooting/questions/old-version-xcode

**Comment by jamesmontemagno** [comment]
I am working with the team to adjust messaging on that alert and to link to docs. It is recommend though to always be on latest.
