### ISSUE TITLE
Android Emulator Issue via Windows 10

### ISSUE THREAD

**Issue by BasemBahig** [xamarin/get-started#71]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/devicesetup
Operating System: windows

The problem as follows: 
When run Android Emulator the laptop gives blue screen and restart.
The code is windows stopper code

**Comment by jamesmontemagno** [comment]
Hmmm. I would read through -> https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/ and see if you will need Intel HAXM or Hyper-V
