### ISSUE TITLE
Fresh install of Community 2019 w/ Xamarin support enabled, and nothing builds

### ISSUE THREAD

**Issue by adamuchi** [xamarin/get-started#73]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/install
Operating System: windows

Nothing builds. Missing Microsoft.UI.Xaml, missing Win2D.uwp, missing NETStandard.LIbrary >= 2.0.3, missing System.Numerics.Vectors >= 4.5.0, missing Microsoft.NETCore.UniversalWindowsPlatform >= 6.2.12. No docs or indication how to get these either. Fundamentally broken experience. Can we get the the docs updated, the installer fixed, and.. some indication of what to do?

**Comment by jamesmontemagno** [comment]
It looks like this is an issue with the UWP project. Have you tried to close the project and re-load it. Additionally do you have the UWP workload installed?

Could you create a new project without UWP selected and see if that works.
