### ISSUE TITLE
Error debugging AwesomApp - missing aapt.exe

### ISSUE THREAD

**Issue by roybillstrom** [xamarin/get-started#74]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/run
Operating System: windows

Followed the tutorial exactly and everything went well, including updating VS2019, and install of Android SDK Build-Tools.  VS found my Samsung tablet. When I clicked Start Debugging, per instructions, I got the following error:
Error		Cannot find `aapt.exe`. Please install the Android SDK Build-Tools package with the `C:\Program Files (x86)\Android\android-sdk\tools\android.bat` program.	AwesomeApp.Android
I did a search of my computer and found the android.bat program at the above location. I also found a file called aapt2.exe at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android, but there is no aapt.exe on my computer.  Any advice?

OK. Got that fixed. Re-installed Android SDK Build-Tools package.

**Comment by jamesmontemagno** [comment]
@redth thoughts?

**Comment by Redth** [comment]
Sounds kind of like it's trying to use aapt instead of aapt2...

https://docs.microsoft.com/en-us/xamarin/android/deploy-test/building-apps/build-properties#androiduseaapt2
