### ISSUE TITLE
Get Windows Blue Screen If Run AVD 

### ISSUE THREAD

**Issue by NoCelestial** [xamarin/get-started#75]
I Have Duplicate Windows (2 Windows 10)

And In Have Two Avd (In First Windows 10 Android Studio & Xamarin Visual Studio AVD) And Other Windows Dos not Have Any Program For Programming In in both Hyper V - Windows Hypervisior Fature Is Enable .

But If I Run Any Android Device My system Has Get Blue Screen "HyperVisior Error " ,"WatchDog Time Out" And I Dont Have Any AntiVirus Just Windows Security

Thanks For Anwser

**Comment by jamesmontemagno** [comment]
Checkout the docs on emulators: https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/
