### ISSUE TITLE
Xaml forms designer

### ISSUE THREAD

**Issue by malkawi2017** [xamarin/get-started#76]
I have the designer view disappeared from visual studio 2019 after updating to the last version. I have many solutions found on the internet (e.g., removing re-shaper, updating, modify regedit, deleting some files, re-install the whole thing) with no luck. Installed visual studio 2017 the designer window is up, but can build the project.

**Comment by jamesmontemagno** [comment]
The XAML Previewer has been deprecated in Visual Studio 2019 version 16.8 and Visual Studio for Mac version 8.8, and replaced by the XAML Hot Reload feature in Visual Studio 2019 version 16.9 and Visual Studio for Mac version 8.9. Learn more about XAML Hot Reload in the documentation.

See: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/hot-reload
