### ISSUE TITLE
xamarin.forums

### ISSUE THREAD

**Issue by aafayad39** [xamarin/get-started#78]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by jamesmontemagno** [comment]
Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
