### ISSUE TITLE
"There was deployement errors.Continue?"

### ISSUE THREAD

**Issue by Manojsingh929** [xamarin/get-started#79]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by jamesmontemagno** [comment]
Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by Manojsingh929** [comment]
thanks for helping, but it have solved the issue.
it was just because of emulater
