### ISSUE TITLE
Error debugging test app

### ISSUE THREAD

**Issue by serenoj** [xamarin/get-started#8]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/run
Operating System: macos

operating system version: Mojave 10.14.6 (18G95)
exact error message:

Error 1:
/Users/dev/Projects/AwesomeApp/AwesomeApp.iOS/clang: Error: linker command failed with exit code 1 (use -v to see invocation) (AwesomeApp.iOS)

Error 2:
/Users/dev/Projects/AwesomeApp/AwesomeApp.iOS/error MT5209: Error: framework not found WatchKit (AwesomeApp.iOS) Native linking

Error 3:
/Users/dev/Projects/AwesomeApp/AwesomeApp.iOS/MTOUCH: Error MT5202: Native linking failed. Please review the build log. (MT5202) (AwesomeApp.iOS)

<img width="1375" alt="Screen Shot 2019-09-27 at 8 14 14 PM" src="https://user-images.githubusercontent.com/1864084/65809488-668c6680-e163-11e9-97ae-63f6ef476bd3.png">

**Comment by jamesmontemagno** [comment]
That is extremely strange. I will ask our development team. Can you run the project and then Report a problem: https://docs.microsoft.com/en-us/visualstudio/mac/report-a-problem?view=vsmac-2019

**Comment by jamesmontemagno** [comment]
So, talked with the team and it looks like perhaps you are on a missmatch of Xcode and Visual Studio for mac. Can you ensure you upgrade Visual Studio for Mac to the latest version and also Xcode to 11.1 (latest). That should fix up this build.
