### ISSUE TITLE
ios simulator

### ISSUE THREAD

**Issue by ehsanzareix** [xamarin/get-started#80]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/devicesetup
Operating System: macos

my vs don't show any iOS simulator and show this message: 
(lower the deployment target to see older simulators or check your apple sdk path)
I have Xcode 12.4 Mac OS catalina 10.15.7 . I tried all deployment targets and I uninstall and install Xcode but nothing changed still no iOS simulator

**Comment by jamesmontemagno** [comment]
Can you ensure you have the command line tools for Xcode installed -> https://developer.apple.com/download/more/?=for%20Xcode

**Comment by ehsanzareix** [comment]
> Can you ensure you have the command line tools for Xcode installed -> https://developer.apple.com/download/more/?=for%20Xcode

i installed that still no ios simulator. when i open vs this message shows up (please install command line tools to enable version control features) 
when i press install now this messege shows up (command line tools installation failed please install git manually open a terminal execute sudo xcode-select__install)
i do that and this message shows up (command line tools are already installed use software update to install updates)

**Comment by jamesmontemagno** [comment]
Hmmmmm yeah that command line stuff for git isn't needed at all. Just the Xcode command line that I linked to.. Can you post some screenshots of Visual Studio for mac?

So it would be great if you could do the report a problem in Visual Studio as that will notify the engineering team.

**Comment by ehsanzareix** [comment]
> Hmmmmm yeah that command line stuff for git isn't needed at all. Just the Xcode command line that I linked to.. Can you post some screenshots of Visual Studio for mac?
> 
> 
> 
> So it would be great if you could do the report a problem in Visual Studio as that will notify the engineering team.

![image](https://user-images.githubusercontent.com/83029929/115793450-d06b0180-a3d4-11eb-8078-dbd61302185c.png)
i executed this command on terminal (sudo rm -rf /Library/Developer/CommandLineTools
xcode-select --install) and that command line tool instal alert gone but still no ios simulator

**Comment by rachelkang** [comment]
@ehsunzar if you haven't already, can you try the following?
- Click on "Debug" and see if there's a "Debug | iPhone Simulator" configuration you can switch to. If so, that's the configuration you need to be on when running the iOS project
- Open a random project in Xcode and check if the simulators are showing up there?
- If you have a physical iPhone device, can you connect it to your Mac and let us know if at least that shows up? (with "Debug | iPhone" configuration if available)

**Comment by ehsanzareix** [comment]
> @ehsunzar if you haven't already, can you try the following?
> 
> - Click on "Debug" and see if there's a "Debug | iPhone Simulator" configuration you can switch to. If so, that's the configuration you need to be on when running the iOS project
> 
> - Open a random project in Xcode and check if the simulators are showing up there?
> 
> - If you have a physical iPhone device, can you connect it to your Mac and let us know if at least that shows up? (with "Debug | iPhone" configuration if available)
> 
> 

if i switch to debug iphone simulator still shows no simulator whith same alert . i can run on my physical device whithout problem . and when i start xcode i have all iphone simulators but no iphone simulator on visual studio

**Comment by rachelkang** [comment]
Hmm interesting... thanks for the update! Can you go to **Visual Studio > Preferences > Projects > SDK Locations > Apple** and see if you have the right path to your Xcode specified there? And if you haven't already, can you try restarting VSMac?

Also, what version of VSMac are you using?

**Comment by ehsanzareix** [comment]
> Hmm interesting... thanks for the update! Can you go to **Visual Studio > Preferences > Projects > SDK Locations > Apple** and see if you have the right path to your Xcode specified there? And if you haven't already, can you try restarting VSMac?
> 
> 
> 
> Also, what version of VSMac are you using?

i have right path xcode specified .
vs version is 8.9.7
vs started showing : please install command line tools to enable version control feauters , again .
i tried to install command line tools as all ways i said before

**Comment by jamesmontemagno** [comment]
Can you check some of the options here -> https://stackoverflow.com/questions/58043820/mac-visual-studio-8-2-6-26-update-not-showing-any-ios-simulators-only-generic-s

Can you open up the info.plist and double check the minimum system and also open up the ios project options and go to iOS Build and check the SDK Version.


The real thing that would help is to go to Help -> Report a Problem so we can look at the logs

**Comment by ehsanzareix** [comment]
> Can you check some of the options here -> https://stackoverflow.com/questions/58043820/mac-visual-studio-8-2-6-26-update-not-showing-any-ios-simulators-only-generic-s
> 
> 
> 
> Can you open up the info.plist and double check the minimum system and also open up the ios project options and go to iOS Build and check the SDK Version.
> 
> 
> 
> 
> 
> The real thing that would help is to go to Help -> Report a Problem so we can look at the logs

when i start a new project default deployment target was 8 with no ios simulator . i tried random deployment tragets and nothing changed.now i started changing deployment target from 14.4 to down one by one at 13.1 deployment target  ios simulators shows up i keep changing deplyoyment tagets to down one by one and for all ; shows ios simulator (between 13.1 to 8.1 deployment target) then i closed vs and open again this time i had all ios simulators whith default deployment target and all yeployment targets (between 14.4 to 7)had ios simulator . i think there was a problem for this issue . now my problem solved but if you whant by help-> report a problem to have a review i can help .
thanks anyway for your help.
