### ISSUE TITLE
Unable to create new project VS Studio 2019 Community edition

### ISSUE THREAD

**Issue by mitvitaminen** [xamarin/get-started#81]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/create
Operating System: windows

Platform: Windows pro, VS2019 community edition, fresh install, selecting mobile app as new project trying to create it I get following error: No command handler is registered for command type Xamarin.VisualStudio.Contracts.Commands.GetVersion please advice this is the first time I install an IDE and it wont work out of the box, wonder if I really should continue my journy into xamarin

**Comment by jamesmontemagno** [comment]
Sorry that you are having issues. Are you able to run a repair on your Visual Studio 2019 installation? That should fix up the issue.
