### ISSUE TITLE
Issue with SDK manager

### ISSUE THREAD

**Issue by mhlm71** [xamarin/get-started#86]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/create
Operating System: windows 10 - 64

I keep facing with the error when I try to run the project:

Error: Xamarin.Android for Visual Studio requires Android SDK. Please click here to configure. [Image](https://s19.picofile.com/file/8433811676/Capture223.JPG)
When I click on it, a window is opened up asking for Android SDK License, after pressing the Accept button it is closed then after some efforts the same error message is appeared.

I updated Visual Studio to Version 16.9.5 but I still see the error message.

If I open up Android SDK manger it asks me to repair [Image](https://s19.picofile.com/file/8433812234/Capture123.JPG)
I click on Repair button then an Accept button, I get the message error saying: "Installing Android SKD tools V26.1.1 failed" [Image](https://s19.picofile.com/file/8433812542/Capture147.JPG)

It has a "1 Update Available" button but again the error occurs ...
I have no idea how to solve the problem. I googled it, I even searched in other related resources but the issue still exists.

**Comment by jamesmontemagno** [comment]
Hmmm it seems like maybe there is an issue in the existing SDK. Can you delete your Android SDK directory and try again? In Visual Studio you can go to Tools -> Options -> Xamarin -> Android Settings -> Android SDK Location.

It is usually: C:\Program Files (x86)\Android\android-sdk

**Comment by mhlm71** [comment]
After spending a few days, finally I figured out that all of these are because of SANCTIONS, I live in Iran and recently google has banned Iranian more strictly rather than before. You can't connect to some google repositories just by ordinary VPNs as you used to, firstly click on [this ](https://dl.google.com/android/repository/sdk-tools-windows-4333796.zip) link, if you see error 403 or 404 you need some solutions to take over it. Since the issue and the solution are not practical for others I don't state it here, email me if you need help: mhlm71@gmail.com
