### ISSUE TITLE
Error with tutorial

### ISSUE THREAD

**Issue by gholl0** [xamarin/get-started#87]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I am on Windows 10 Pro on version 20H2. I was following the xamarin forms tutorial and when I ran the start debugging portion my build failed to run and I got this error:
Severity	Code	Description	Project	File	Line	Suppression State
Error		The SDK 'Microsoft.NET.Sdk' specified could not be found.	AwesomeApp.Android	C:\...\repos\AwesomeApp\AwesomeApp\AwesomeApp\AwesomeApp.csproj		

I am not sure how to fix this and everything I found online was about adding variables to the environment and whatnot. I am not very savvy with virtual studio so I have no idea how to fix this. Thanks in advance!

**Comment by jamesmontemagno** [comment]
Are you running in Visual Studio or Rider?

Would look at https://github.com/dotnet/msbuild/issues/2532 or try to run a repair on Visual Studio to re-install .NET Core

**Comment by gholl0** [comment]
I found a solution: https://github.com/dotnet/msbuild/issues/4858. Thanks for the help!
