### ISSUE TITLE
qemu-system-i386.exe has stopped working LenovoIdeapad 700 I7 12Gb Emulator shows at start before no Hello world

### ISSUE THREAD

**Issue by mostmarc** [xamarin/get-started#9]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by jamesmontemagno** [comment]
Hey there, sorry you are having issues with the emulator. can you follow through our troubleshooting guide: https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/troubleshooting?pivots=windows or perhaps run in on a device.
