### ISSUE TITLE
There is no any MainPage.xaml

### ISSUE THREAD

**Issue by krasnikau-andrei** [xamarin/get-started#92]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

There is no MainPage.xaml file. In Errors list I see this 
![image](https://user-images.githubusercontent.com/25789888/121654330-4a02a000-caa6-11eb-8a3a-100d22eb1d07.png)

**Comment by jamesmontemagno** [comment]
It looks like perhaps there is something wrong with your Installation of visual studio. Can you run a repair on it?

I would love to see what the solution looks like as well.

**Comment by jamesmontemagno** [comment]
If you could even package it up and share that would be great.
