### ISSUE TITLE
Provide feedback button just reloads the page.

### ISSUE THREAD

**Issue by dunks184** [xamarin/get-started#93]
Problem encountered on https://dotnet.microsoft.com/learn/xamarin/hello-world-tutorial/modify#
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I wanted to provide some feedback* but the Provide Feedback button doesn't work. It just reloads the tutorial page.

*the button should be added without a click handler at first otherwise the build fails which initially confused me briefly

**Comment by jamesmontemagno** [comment]
👍 I think that is a good change. I will make it before the code behind stuff.

**Comment by mairaw** [comment]
@dunks184 can you provide more information about the issue you're having with the Feedback button?
